#!/bin/bash
# MasterScript: Phase 1 of mosaic variant finding pipeline, which includes
# 1. Coverage Analysis of every bam file
# 2. GATK-HC: germline variant calling in each family
# 3. Mutect2: Parents and Probands and Siblings (if available)
# 4. MosaicHunter: Parents and Probands and Siblings (if available)
# 5. MosaicForecast on Mutect2 variant callset
# UniAdelaide-HPC friendly
# Date: 9th June 2023

## Set hard-coded paths and define functions ##
SCRIPTDIR="/hpcfs/groups/phoenix-hpc-neurogenetics/scripts/git/neurocompnerds/map-n-call"
LOGDIR="/hpcfs/users/${USER}/log"

if [ ! -d "${logDir}" ]; then
    mkdir -p ${logDir}
    echo "## INFO: New log directory created, you'll find all of the log information from this pipeline here: ${logDir}"
fi

usage()
{
echo "#MasterScript: Phase 1 of mosaic variant finding pipeline, which includes
# 1. Coverage Analysis of every bam file
# 2. GATK-HC: germline variant calling in each family
# 3. Mutect2: Parents and Probands and Siblings (if available)
# 4. MosaicHunter: Parents and Probands and Siblings (if available)
# 5. MosaicForecast on Mutect2 variant callset
#
# Requires: 
#
# Usage $0 -p file_prefix -s /path/to/sequences -o /path/to/output -c /path/to/config.cfg -S Sample -L LIBRARY -I ID] | [ - h | --help ]
#
# Options
#-s REQUIRED sampleID list
#-b REQUIRED Bamfile directory 
#-o REQUIRED Output directory
#-r REQUIRED Referencegenome (i.e /hpcfs/groups/phoenix-hpc-neurogenetics/RefSeq/hs37d5.fa)
#-p OPTIONAL PanelOfNormal (i.e /gpfs/users/a1149120/GA_Mutect2_ReCalling/PON
# -h or --help  Prints this message.  Or if you got one of the options above wrong you'll be reading this too!
#
# Original: Nandini Sandran, 9/6/2023
# Modified: (Date; Name; Description)
# 
#
#
"
}

## Set Variables ##
while [ "$1" != "" ]; do
        case $1 in
                -s )                    shift
                                        SAMPLEID=$1
                                        ;;
                -b )                    shift
                                        BAM=$1
                                        ;;
               	-o )                    shift
                                        OUTDIR=$1
                                        ;;
                -r )                    shift
                                        REFGEN=$1
                                       	;;
                -p )                    shift
                                        PONDIR=$1
                                        ;;
                * )                     usage
                                        exit 1
        esac
        shift
done

#Define variables from SAMPLEID list file
Proband=
ProbandGender=
Sibling=
SiblingGender=
Mother=
Father=

#VARIANT CALLER1: MOSAICHUNTER
#MosaicHunter variant calling in probands
sbatch $DIR/MosaicHunter_WES_Trio_GA.sh -s $Proband -b $BAM -d $OUTDIR -g $ProbandGender -r $REFGEN
#MosaicHunter variant calling in siblings if there is
sbatch $DIR/MosaicHunter_WES_Trio_GA.sh -s $Sibling -b $BAM -d $OUTDIR -g $SiblingGender -r $REFGEN
#MosaicHunter variant calling in father if there is
sbatch $DIR/MosaicHunter_WES_Singlemode_GA.sh -s $Father -b $BAM -d $OUTDIR -g M -r $REFGEN
#MosaicHunter variant calling in mother if there is
sbatch $DIR/MosaicHunter_WES_Singlemode_GA.sh -s $Mother -b $BAM -d $OUTDIR -g F -r $REFGEN

#VARIANT CALLER 2: MUTECT2
#Mutect2: variant calling in Probands
#check if PON contains the the sample that we are testing, or else use different PON


#Execute Mutect2 for probands
MUT_Pro='sbatch Mutect2.singlemode.sh -b $BAM -m $MUTDIR-s $Proband -d $OUTDIR -r $REF'
#Execute Mutect2 for sibling
MUT_Sib='sbatch Mutect2.singlemode.sh -b $BAM -m $MUTDIR-s $Sibling -d $OUTDIR -r $REF'
#Execute Mutect2 for father
MUT_Fa='sbatch Mutect2.singlemode.sh -b $BAM -m $MUTDIR-s $Father -d $OUTDIR -r $REF'
#Execute Mutect2 for mother
MUT_Mo='sbatch Mutect2.singlemode.sh -b $BAM -m $MUTDIR-s $Mother -d $OUTDIR -r $REF'

#VARIANT CALLER 3: MOSAICFORECAST
#This has to be executed only after Mutect2 is completed
#Preprocess (this are just commands)
sbatch --export=ALL --dependency=afterok:${MUT_Pro} 
